### PR TITLE
[TOSA] Fix result type for Conv1D operations.

### PR DESCRIPTION
**Pull request by ttjost**
Conv1D simplication had a wrong output type. This PR fixes the issue.

### CODE REVIEW

**Comment by mgehre-amd** [comment]
Why did this not come up in the end2end tests? Should we have an end2end test covering this?

**Review by mgehre-amd — APPROVED** [review]
LGTM, but check end2end test

**Comment by ttjost** [comment]
> Why did this not come up in the end2end tests? Should we have an end2end test covering this?

So, we didn't see it before because we were only doing non-group Conv1D, and the type was not properly set for Group convolution. I will for #78  to get merged and then update this PR with a test for it.

**Comment by ttjost** [comment]
I added a test that covers this issue.

**Pull request merged**
