### PR TITLE
Reduce our diff compared to upstream

### PR DESCRIPTION
**Pull request by mgehre-amd**
by dropping changes that gained upstream support.
E.g. `EyeStaticModule` has an identical test case with a different name

This should reduce the amount of merge conflicts in the next bump.

### CODE REVIEW

**Comment by cferry-AMD** [comment]
Thanks! Is this a breaking change? I guess we should merge this just before the bump, or bump on top of this commit so we never "lose" anything.

**Comment by mgehre-amd** [comment]
> Thanks! Is this a breaking change? I guess we should merge this just before the bump, or bump on top of this commit so we never "lose" anything.

No, this is not breaking from what I know. I would merge this PR  and then start bumping afterwards.

**Review by cferry-AMD — APPROVED** [review]
Fine by me, we can always revert this if we're in trouble bumping. Out of curiosity, given the large change set in the codebase, what prompted you to select these?

**Comment by mgehre-amd** [comment]
> Fine by me, we can always revert this if we're in trouble bumping. Out of curiosity, given the large change set in the codebase, what prompted you to select these?

Partly those were things I remembered, and partly I looked at the diff between our merge base with upstream and the branch. I did this while re-organizing https://github.com/Xilinx/torch-mlir/issues/70, which we used in the early days.

**Pull request merged**
