### PR TITLE
Emit explicit error for unsupported modes of onnx.Pad

### PR DESCRIPTION
**Pull request by josel-amd**

### CODE REVIEW

**Review by mgehre-amd — CHANGES_REQUESTED** [review]
Looking at this closer, `DecomposeAtenPadOp` seems to be the actual culprit because it ignores the `mode` attribute when lowering.

**Review by mgehre-amd — APPROVED** [review]
Thanks!

**Comment by mgehre-amd** [comment]
Can you please also backport to the `release_rai_1.2` branch?

**Review by TinaAMD — APPROVED** [review]
Very nice!

**Pull request merged**
